global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'event-ingestion'
    static_configs:
      - targets: ['localhost:8080']
    metrics_path: '/metrics'

  - job_name: 'session-manager'
    static_configs:
      - targets: ['localhost:8081']
    metrics_path: '/metrics'

  - job_name: 'ufse'
    static_configs:
      - targets: ['localhost:8082']
    metrics_path: '/metrics'

  - job_name: 'incident-store'
    static_configs:
      - targets: ['localhost:8084']
    metrics_path: '/metrics'

  - job_name: 'ticket-exporter'
    static_configs:
      - targets: ['localhost:8085']
    metrics_path: '/metrics'
